apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: o3timorti-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/o3timorti-java-quarkus-gitops